const wordList = {
    1: ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'],
    2: ['at', 'in', 'on', 'up', 'do', 'go', 'hi', 'me', 'my', 'no', 'of', 'ox', 'to', 'us', 'we', 
        'am', 'ax', 'ay', 'be', 'by', 'da', 'ed', 'eh', 'em', 'er', 'es', 'et', 'fa', 'ha', 'he', 
        'ho', 'id', 'la', 'ma', 'pa', 're', 'si', 'ta', 'ti', 'um', 'ya', 'ye', 'ah', 'bi', 'bo', 
        'de', 'ef', 'ex', 'gi', 'gu', 'if', 'is', 'it', 'jo', 'ka', 'ki', 'li', 'lo', 'mi', 'mo', 
        'mu', 'na', 'ne', 'ni', 'nu', 'od', 'om', 'op', 'or', 'os', 'pe', 'pi', 'po', 'qi', 'se', 
        'so', 'te', 'ti', 'un', 'ut', 'va', 'vi', 'wo', 'xi', 'xu', 'za', 'zo',
        'an', 'as', 'or', 'it', 'so', 'we', 'he', 'she', 'if', 'or', 'us', 'by', 'my', 'oh', 'ok',
        'hi', 'yo', 'ad', 'ag', 'ah', 'ai', 'al', 'ar', 'aw', 'ay', 'ba', 'da', 'di', 'du', 'eh'],
    3: ['cat', 'dog', 'sun', 'run', 'red', 'sea', 'box', 'bat', 'ant', 'bee', 'cow', 'fox', 'pig', 'rat', 
        'ape', 'ark', 'ask', 'bag', 'bay', 'bed', 'bit', 'bug', 'bus', 'can', 'cap', 'car', 'cup', 'day', 'dig', 
        'dip', 'dot', 'ear', 'egg', 'end', 'fan', 'far', 'fat', 'fit', 'fly', 'for', 'fun', 'gap', 'gas', 'get', 
        'gun', 'hat', 'hen', 'hop', 'hot', 'hug', 'hut', 'ice', 'ink', 'jar', 'jog', 'joy', 'jug', 'kit', 'lay', 
        'let', 'lid', 'lip', 'lit', 'man', 'mat', 'may', 'men', 'mud', 'mug', 'nap', 'nod', 'not', 'nut', 'oil', 
        'old', 'one', 'out', 'owl', 'pan', 'pen', 'pet', 'pie', 'pin', 'pop', 'pot', 'put', 'rag', 'ram', 'ran', 
        'rap', 'rip', 'row', 'rub', 'rug', 'sad', 'saw', 'say', 'see', 'set', 'sew', 'shy', 'sit', 'ski', 'sky', 
        'sob', 'son', 'sow', 'spy', 'tap', 'tar', 'tea', 'ted', 'ten', 'tie', 'tin', 'tip', 'toe', 'ton', 'top', 
        'toy', 'try', 'tub', 'two', 'use', 'van', 'vat', 'way', 'wet', 'why', 'win', 'won', 'yet', 'zoo',
        'air', 'and', 'any', 'art', 'bad', 'big', 'boy', 'but', 'can', 'eat', 'eye', 'few', 'fun', 'get', 'got',
        'had', 'has', 'her', 'him', 'his', 'how', 'its', 'key', 'law', 'let', 'man', 'new', 'now', 'old', 'our'],
    4: ['fish', 'blue', 'swim', 'deep', 'dark', 'sand', 'crab', 'clam', 'wave', 'ship', 'boat', 'sail', 
        'able', 'ache', 'acid', 'acre', 'aged', 'aide', 'ally', 'also', 'amen', 'ammo', 'ankh', 'aqua', 'arch', 'area', 
        'army', 'atom', 'aunt', 'aura', 'auto', 'avid', 'awed', 'babe', 'baby', 'back', 'bake', 'bald', 'ball', 'band', 
        'bank', 'bare', 'bark', 'barn', 'base', 'bath', 'bead', 'beam', 'bean', 'bear', 'beat', 'beef', 'beer', 'bell', 
        'belt', 'bend', 'best', 'bike', 'bill', 'bird', 'bite', 'blow', 'blue', 'boat', 'body', 'bolt', 'bone', 'book', 
        'boom', 'boot', 'born', 'boss', 'both', 'bowl', 'brag', 'brim', 'bulb', 'bull', 'burn', 'bush', 'busy', 'butt', 
        'cage', 'cake', 'call', 'calm', 'came', 'camp', 'cane', 'cape', 'card', 'care', 'cart', 'case', 'cash', 'cast', 
        'cave', 'cell', 'cent', 'chap', 'chat', 'chef', 'chew', 'chin', 'chip', 'chop', 'city', 'clad', 'clap', 'clay', 
        'clip', 'club', 'coal', 'coat', 'code', 'coin', 'cold', 'comb', 'come', 'cook', 'cool', 'cope', 'copy', 'cord', 
        'core', 'cork', 'corn', 'cost', 'coup', 'cove', 'crap', 'crew', 'crop', 'crow', 'cube', 'cult', 'cure', 'curl',
        'bird', 'book', 'cake', 'card', 'door', 'easy', 'face', 'game', 'girl', 'hand', 'home', 'idea', 'jump', 'king',
        'lady', 'life', 'love', 'moon', 'name', 'open', 'play', 'rain', 'road', 'ship', 'star', 'time', 'tree', 'walk',
        'wall', 'wind', 'work', 'year', 'zest', 'zone', 'zoom', 'zero', 'yard', 'yarn'],
    5: ['shark', 'whale', 'ocean', 'beach', 'coral', 'diver', 'water', 'storm', 'depth', 'light', 
        'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adore', 'adult', 'after', 'again', 'agent', 'agree', 'ahead', 
        'aisle', 'alarm', 'album', 'alert', 'alike', 'alive', 'allow', 'alone', 'along', 'aloud', 'alpha', 'altar', 'amber', 'amend', 
        'angel', 'anger', 'angle', 'angry', 'ankle', 'annoy', 'apart', 'apple', 'apply', 'apron', 'arena', 'argue', 'arise', 'armor', 
        'aroma', 'array', 'arrow', 'ashes', 'aside', 'asset', 'atlas', 'audio', 'audit', 'avoid', 'awake', 'award', 'aware', 'awful', 
        'badge', 'badly', 'bagel', 'baker', 'balls', 'banal', 'bandy', 'banjo', 'barge', 'barns', 'baron', 'basic', 'basil', 'basis', 
        'batch', 'baton', 'beach', 'beads', 'beams', 'beans', 'beard', 'bears', 'beast', 'began', 'begin', 'begun', 'being', 'belly', 
        'below', 'bench', 'berry', 'bible', 'biked', 'biker', 'bingo', 'birth', 'bison', 'bites', 'black', 'blade', 'blame', 'blank',
        'apple', 'brain', 'brave', 'bread', 'brown', 'chair', 'cloud', 'dance', 'dream', 'earth', 'fairy', 'field', 'flame', 'fleet',
        'flower', 'ghost', 'green', 'happy', 'heart', 'house', 'juice', 'kitty', 'knife', 'lemon', 'light', 'money', 'music', 'night',
        'ocean', 'party', 'piano', 'pizza', 'queen', 'river', 'smile', 'sugar', 'table', 'tiger', 'water', 'watch', 'white', 'world'],
    6: ['pirate', 'anchor', 'island', 'vessel', 'sailor', 'oyster', 'shrimp', 'squids', 'jelly', 
        'abacus', 'abased', 'abated', 'abbeys', 'abbots', 'abduct', 'abhors', 'abided', 'abject', 'abjure', 'ablate', 'ablaze', 'aboard', 
        'abodes', 'aborts', 'abound', 'abrade', 'abroad', 'abrupt', 'absent', 'absorb', 'absurd', 'abused', 'abuser', 'abuses', 'acacia', 
        'accede', 'accent', 'accept', 'access', 'accord', 'accost', 'accrue', 'accuse', 'acetic', 'acetyl', 'aching', 'acidic', 'acorns', 
        'across', 'acting', 'action', 'active', 'actors', 'actual', 'acuity', 'acumen', 'adages', 'adagio', 'adapts', 'addend', 'adders', 
        'addict', 'adding', 'addled', 'adduce', 'adduct', 'adepts', 'adhere', 'adipic', 'adjoin', 'adjust', 'admire', 'admits', 'adobes', 
        'adopts', 'adored', 'adores', 'adorns', 'adrift', 'adroit', 'adsorb', 'adults', 'advent', 'adverb', 'advert', 'advice', 'advise', 
        'aerate', 'aerial', 'affair', 'affect', 'affirm', 'afford', 'afghan', 'afield', 'aflame', 'afloat', 'afraid', 'afresh', 'agates',
        'animal', 'basket', 'beauty', 'butter', 'camera', 'candle', 'castle', 'coffee', 'cookie', 'dinner', 'dragon', 'family', 'garden',
        'guitar', 'hockey', 'jacket', 'kitten', 'laptop', 'letter', 'market', 'monkey', 'mother', 'orange', 'pencil', 'planet', 'pocket',
        'rocket', 'school', 'shadow', 'sister', 'spider', 'summer', 'sunset', 'ticket', 'turtle', 'window', 'winter', 'yellow', 'zebra'],
    7: ['dolphin', 'captain', 'lobster', 'seaside', 'current', 'tsunami', 'surface', 'fishing', 
        'abalone', 'abandon', 'abashed', 'abasing', 'abaters', 'abating', 'abators', 'abaxial', 'abbotcy', 'abdomens', 'abelian', 'abettor', 
        'abeyant', 'abiding', 'ability', 'abioses', 'abiosis', 'abiotic', 'abjured', 'abjurer', 'abjures', 'ablated', 'ablates', 'ablator', 
        'ablauts', 'ableism', 'ableist', 'abloom', 'abluted', 'aboding', 'abolish', 'abomasa', 'abomasi', 'aborted', 'aborter', 'abortus', 
        'aboulia', 'abounds', 'abraded', 'abrader', 'abrades', 'abreact', 'abreast', 'abridge', 'abroach', 'abrosia', 'abscise', 'abscond', 
        'abseils', 'absence', 'absents', 'absinth', 'absolve', 'absorbs', 'abstain', 'abusers', 'abusing', 'abusive', 'abuttal', 'abutted', 
        'abutter', 'abysmal', 'abyssal', 'acacias', 'academe', 'academy', 'acajous', 'acaleph', 'acanthi', 'acapnia', 'acarids', 'acarine', 
        'acaudal', 'acceded', 'acceder', 'accedes', 'accents', 'accepts', 'accidia', 'accidie', 'acclaim', 'accords', 'accosts', 'account',
        'airport', 'bedroom', 'birthday', 'biscuit', 'brother', 'chicken', 'company', 'diamond', 'evening', 'football', 'freedom', 'friends',
        'holiday', 'kitchen', 'library', 'morning', 'mountain', 'network', 'package', 'picture', 'rainbow', 'restaurant', 'sandwich',
        'science', 'station', 'student', 'teacher', 'television', 'theater', 'universe', 'vacation', 'weather', 'weekend', 'welcome'],
    8: ['stingray', 'plankton', 'starfish', 'barnacle', 'seahorse', 'predator', 'maritime', 
        'aardvark', 'abacuses', 'abalones', 'abampere', 'abandoned', 'abandonee', 'abandoner', 'abasement', 'abashedly', 'abashment', 
        'abatement', 'abattoirs', 'abbacies', 'abbatial', 'abbesses', 'abdicate', 'abdomens', 'abducted', 'abductee', 'abductor', 
        'aberrant', 'abetment', 'abettors', 'abeyance', 'abhorred', 'abhorrer', 'abidance', 'abigails', 'abjectly', 'abjurers', 
        'abjuring', 'ablating', 'ablation', 'ablative', 'ablators', 'ablegate', 'ableisms', 'ableists', 'ablepsia', 'ablution', 
        'abnegate', 'abnormal', 'abomasum', 'abomasus', 'aborally', 'aborning', 'abortion', 'abortive', 'abounded', 'abrachia', 
        'abradant', 'abraders', 'abrading', 'abrasion', 'abrasive', 'abreacts', 'abridged', 'abridger', 'abridges', 'abrogate', 
        'abrosias', 'abrupter', 'abruptly', 'abscised', 'abscises', 'abscisin', 'abscissa', 'absconds', 'abseiled', 'absentee', 
        'absenter', 'absently', 'absinthe', 'absinths', 'absolute', 'absolved', 'absolver', 'absolves', 'absorber', 'abstains',
        'airplane', 'birthday', 'breakfast', 'butterfly', 'calendar', 'chocolate', 'computer', 'dinosaur', 'elephant', 'football',
        'hospital', 'internet', 'keyboard', 'language', 'magazine', 'notebook', 'password', 'question', 'shopping', 'swimming',
        'telephone', 'tomorrow', 'umbrella', 'vacation', 'waterfall', 'wednesday', 'yourself', 'basketball', 'chocolate', 'classroom'],
    9: ['jellyfish', 'submarine', 'coastline', 'shipwreck', 'whirlpool', 'harpooner', 
        'aardvarks', 'abamperes', 'abandoned', 'abandonee', 'abandoner', 'abasement', 'abashment', 'abatement', 'abattoirs', 
        'abbotcies', 'abbotcies', 'abdicable', 'abdicated', 'abdicates', 'abdicator', 'abdominal', 'abducting', 'abduction', 
        'abductors', 'aberrance', 'aberrancy', 'aberrants', 'abetments', 'abeyances', 'abhenries', 'abhorrence', 'abhorrent', 
        'abhorrers', 'abhorring', 'abidances', 'abilities', 'abjection', 'abjective', 'abjurious', 'abnegated', 'abnegates', 
        'abnegator', 'abnormals', 'abnormity', 'abolished', 'abolisher', 'abolishes', 'abolition', 'abomasums', 'aboriginal', 
        'aborigine', 'abortions', 'abortuses', 'abounding', 'abrachias', 'abradants', 'abrasions', 'abrasives', 'abreacted', 
        'abreges', 'abridgers', 'abridging', 'abrogated', 'abrogates', 'abrogator', 'abruptest', 'abscising', 'abscisins', 
        'abscissae', 'abscissas', 'abscissin', 'absconded', 'absconder', 'absentees', 'absenters', 'absenting', 'absinth', 
        'absolutes', 'absolvent', 'absolving', 'absorbant', 'absorbent', 'absorbers', 'absorbing', 'abstained', 'abstainer',
        'adventure', 'beautiful', 'breakfast', 'chocolate', 'crocodile', 'dictionary', 'education', 'fireplace', 'friendship',
        'hamburger', 'happiness', 'important', 'invention', 'knowledge', 'landscape', 'moonlight', 'northwest', 'pineapple',
        'restaurant', 'sandwich', 'spaghetti', 'strawberry', 'sunflower', 'telephone', 'television', 'transport', 'university',
        'vegetable', 'watermelon', 'waterfall', 'wednesday', 'whisper', 'yesterday', 'zookeeper'],
    10: ['lighthouse', 'underwater', 'barracuda', 'expedition', 'navigation', 
         'abandoning', 'abandonment', 'abasedness', 'abatements', 'abbreviate', 'abdicating', 'abdication', 'abdominals', 
         'abducentes', 'abductions', 'aberrantly', 'aberrating', 'aberration', 'abetments', 'abhorrence', 'abhorrents', 
         'abjectness', 'abjuration', 'abjuringly', 'ablatively', 'ablepharia', 'ablutionary', 'abnegating', 'abnegation', 
         'abnegators', 'abnormally', 'abnormities', 'abolishing', 'abolishment', 'abolition', 'abominable', 'abominably', 
         'abominated', 'abominates', 'abominator', 'aboriginal', 'aborigines', 'aborticide', 'abortively', 'abouchement', 
         'aboundingly', 'aboutfaced', 'aboutfaces', 'aboveboard', 'abracadabra', 'abranchial', 'abrasively', 'abreaction', 
         'abreactive', 'abridgment', 'abrogating', 'abrogation', 'abrogative', 'abrogators', 'abruptness', 'abscessing', 
         'abscession', 'abscission', 'absconders', 'absconding', 'abseilings', 'absentminded', 'absinthism', 'absolutely', 
         'absolutest', 'absolution', 'absolutism', 'absolutist', 'absolutory', 'absolvable', 'absorbable', 'absorbance', 
         'absorbency', 'absorbents', 'absorptance', 'absorptive', 'abstainers', 'abstaining', 'abstemious', 'abstention',
         'apparently', 'basketball', 'chocolate', 'difference', 'everything', 'experience', 'frequently', 'generation',
         'helicopter', 'impossible', 'individual', 'leadership', 'management', 'particular', 'reflection', 'relaxation',
         'scientific', 'strawberry', 'television', 'understand', 'vegetables', 'watermelon', 'wilderness', 'wonderful',
         'yellowstone', 'zoological', 'birthplace', 'friendship', 'happiness', 'homework', 'internship', 'notebook'],
    11: ['oceaniclife', 'treacherous', 'unsinkable', 'shipbuilder', 
         'abandonment', 'abbreviated', 'abbreviates', 'abbreviator', 'abdications', 'abdominally', 'abducens', 
         'abductions', 'abductores', 'aberrations', 'abiotically', 'abjurations', 'ablactation', 'ablatively', 
         'ablegations', 'abnegations', 'abnormality', 'abnormities', 'abolishable', 'abolishment', 'abominable', 
         'abominably', 'abominating', 'abomination', 'abominators', 'abortionist', 'abortively', 'aboveground', 
         'abracadabra', 'abranchiate', 'abreactions', 'abridgement', 'abridgments', 'abrogations', 'abruptness', 
         'absentminded', 'absinthism', 'absolutisms', 'absolutists', 'absorbances', 'absorbently', 'absorbingly', 
         'absorptance', 'absorptivity', 'abstentious', 'abstentions', 'abstergents', 'abstinence', 'abstinency', 
         'abstracted', 'abstracter', 'abstracting', 'abstraction', 'abstractive', 'abstractly', 'abstractors', 
         'abstrusely', 'abstrusest', 'abstrusity', 'absurdities', 'absurdness', 'abundances', 'abundantly', 
         'abusedness', 'abusiveness', 'abutter', 'abysmally', 'abyssal', 'academical', 'academically', 'academician',
         'celebration', 'championship', 'cooperation', 'development', 'educational', 'electricity', 'engineering',
         'environment', 'explanation', 'information', 'interesting', 'opportunity', 'performance', 'preparation',
         'recognition', 'responsible', 'scholarship', 'significant', 'temperature', 'transportation', 'university',
         'volunteering', 'waterfall', 'yellowstone', 'zoological', 'biodiversity', 'butterflies', 'chocolate', 'friendship'],
    12: ['oceanography', 'invertebrate', 'mediterranean', 'biodiversity', 
         'abandonments', 'abbreviation', 'abbreviators', 'abbreviatory', 'abdications', 'abdominally', 'abducentes', 
         'aberrational', 'abiogenesis', 'abiogeneses', 'abiogenist', 'abiological', 'abiotically', 'abirritants', 
         'abirritated', 'abirritates', 'abjectness', 'abjurations', 'ablactating', 'ablactation', 'ablation', 
         'ablutionary', 'abnegations', 'abnormalcies', 'abnormality', 'abolishable', 'abolishment', 'abominable', 
         'abominably', 'abominating', 'abomination', 'abominators', 'aboriginal', 'abortionist', 'abortively', 
         'abovementioned', 'abracadabra', 'abranchiate', 'abreactions', 'abridgement', 'abridgments', 'abrogations', 
         'abruptness', 'absenteeism', 'absentminded', 'absinthism', 'absolutisms', 'absolutists', 'absolvatory', 
         'absorbancy', 'absorbances', 'absorbefacient', 'absorbencies', 'absorbently', 'absorbingly', 'absorptance', 
         'absorptivity', 'abstentious', 'abstentions', 'abstergents', 'abstinence', 'abstinency', 'abstracted', 
         'abstracter', 'abstracting', 'abstraction', 'abstractive', 'abstractly', 'abstractors', 'abstrusely',
         'appreciation', 'architecture', 'communication', 'conservation', 'construction', 'entertainment', 'grandparents',
         'independence', 'intermediate', 'international', 'introduction', 'photography', 'professional', 'relationship',
         'reproduction', 'satisfaction', 'scholarship', 'significance', 'sustainability', 'technological', 'transportation',
         'understanding', 'unforgettable', 'weatherproof', 'yellowstone', 'zoological', 'agriculture', 'astronomical', 'celebration'],
    13: [
        'abbreviations', 'accomplishment', 'administration', 'agricultural', 'anniversary', 'approximately', 'archaeological',
        'authorization', 'autobiography', 'bacteriological', 'bibliographic', 'cardiovascular', 'certification', 'characteristic',
        'collaboration', 'communication', 'comprehension', 'confidential', 'congratulation', 'consciousness', 'constitutional',
        'contamination', 'contradiction', 'cooperatively', 'demonstration', 'determination', 'development', 'differentiate',
        'documentation', 'electricity', 'entertainment', 'environmental', 'extraordinary', 'foundation', 'generalization',
        'geographical', 'identification', 'imagination', 'immigration', 'incorporation', 'infrastructure', 'inspiration',
        'instruction', 'international', 'interpretation', 'investigation', 'justification', 'manufacturing', 'multinational',
        'organization', 'participation', 'photographic', 'presidential', 'productivity', 'psychological', 'qualification',
        'questionnaire', 'recommendation', 'rehabilitation', 'relationship', 'representation', 'responsibility',
        'satisfaction', 'scholarship', 'sophisticated', 'specification', 'superintendent', 'technological', 'transformation',
        'transportation', 'understanding', 'unfortunately', 'university', 'vulnerability', 'weatherproof', 'welcoming'
    ],
    14: [
        'abnormalities', 'accountability', 'accreditation', 'administrative', 'advertisement', 'anthropological',
        'appreciation', 'authentication', 'autobiographic', 'characteristics', 'classification', 'communication',
        'comprehension', 'comprehensive', 'concentration', 'confidentiality', 'congratulation', 'constitutional',
        'contamination', 'contradiction', 'conversational', 'correspondence', 'counterfeit', 'crystallization',
        'demonstration', 'determination', 'differentiate', 'discrimination', 'documentation', 'entrepreneurial',
        'environmental', 'establishment', 'extraordinary', 'fundamental', 'generalization', 'identification',
        'implementation', 'improvisation', 'incorporation', 'indispensable', 'infrastructure', 'investigation',
        'justification', 'maintenance', 'manufacturing', 'misunderstanding', 'nationalization', 'notification',
        'organization', 'personalization', 'photosynthesis', 'precipitation', 'procrastination', 'pronunciation',
        'qualification', 'questionnaire', 'recommendation', 'reconciliation', 'rehabilitation', 'representation',
        'responsibility', 'revolutionary', 'satisfaction', 'scholarship', 'specialization', 'specification',
        'standardization', 'superintendent', 'telecommunication', 'transportation', 'understanding', 'unprecedented',
        'vulnerability', 'weatherproofing', 'wellwishing'
    ],
    15: [
        'acclimatization', 'bouillabaisse', 'cannibalization', 'choreographers', 'correspondence', 
        'disappointment', 'excommunication', 'exemplification', 'existentialism', 'hallucinations', 
        'inaccessibility', 'inconsiderable', 'indiscriminate', 'interconnected', 'irresponsibility',
        'acknowledgement', 'administrations', 'rationalization', 'standardization', 'transformations', 
        'personification', 'intensification', 'disorganization', 'confidentiality', 'competitiveness', 
        'autobiographies', 'accomplishments', 'acknowledgments', 'bacteriological', 'crystallization'
    ],
    16: [
        'bioavailability', 'characterization', 'contraindication', 'decentralization', 'disqualification', 
        'extinguishment', 'incomprehensible', 'indistinguishable', 'interdisciplinary', 'microelectronics', 
        'misinterpretation', 'mispronunciation', 'neurotransmitter', 'paralinguistics', 'responsibilities',
        'journalistically', 'knowledgeability', 'methodologically', 'multiculturalism', 'subconsciousness', 
        'transcontinental', 'compartmentalize', 'counteroffensive', 'autobiographical', 'circumstantially', 
        'consequentialism', 'conservationists', 'constructionists', 'counterarguments', 'counterespionage'
    ],
    17: [
        'compartmentalized', 'conceptualization', 'counterargument', 'counterterrorism', 'electrocardiogram', 
        'environmentalists', 'hydroelectricity', 'industrialization', 'interdepartmental', 'intergovernmental', 
        'misrepresentation', 'misunderstanding', 'telecommunication', 'underappreciated', 'unprofessionalism',
        'multidisciplinary', 'intercommunicated', 'bureaucratization', 'comprehensibility', 'decriminalization', 
        'denationalization', 'deterministically', 'inappropriateness', 'incompatibilities', 'indestructibility', 
        'interrelationship', 'maladministration', 'nondiscriminatory', 'commercialisation', 'conceptualisation'
    ],
    18: [
        'characteristically', 'commercialization', 'constitutionalism', 'constructivism', 'conversationalists', 
        'counterproductive', 'cryptozoologists', 'electrocardiograph', 'immunofluorescence', 'institutionalizing', 
        'multidimensional', 'neuropsychological', 'oversimplification', 'photoluminescence', 'sentimentalization',
        'interchangeability', 'telecommunications', 'contradistinctions', 'histocompatibility', 'disproportionately', 
        'autobiographically', 'constitutionalists', 'counterrevolutions', 'deinstitutionalize', 'disenfranchisement', 
        'electrocardiograms', 'internationalizing', 'misrepresentations', 'anticonstitutional', 'antidiscrimination'
    ]
};